### ISSUE TITLE
no protocol issue again

### ISSUE THREAD

**Issue by mis3250** [himukr/google-grp-scraper#1]
Hi:

Thanks for your fast response. I have added an environment variable _GROUP and I still have the following no protocol  error:

C:\maven\googleGroup\google-grp-scraper\target>java -jar google-grp-scraper-0.0.
1-SNAPSHOT.jar 'https://groups.google.com/forum/#!forum/ibm.software.websphere.a
pplication-server' 20
Exception in thread "main" java.net.MalformedURLException: no protocol: 'https:/
/groups.google.com/forum/#!forum/ibm.software.websphere.application-server'
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at com.pramati.scraper.google_grp_scraper.ScraperStartup.main(ScraperSta
rtup.java:9)

Thanks again.

**Comment by himanshukhantwal** [comment]
closed with other issue.
