### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ghost** [himukr/google-grp-scraper#4]
Downloaded project.  Installed Maven.  Ran mvn clean install.  Attempting to run scraper results in the following:

java -jar target\google-grp-scraper-0.0.1-SNAPSHOT.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/WebDriver
        at com.pramati.scraper.google_grp_scraper.ScraperStartup.main(ScraperStartup.java:8)

Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WebDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

**Comment by himanshukhantwal** [comment]
hi,
you are running it without its dependency jars.
try running application using  maven-exec-plugin 
http://stackoverflow.com/questions/9846046/run-main-class-of-maven-project

Thanks.
